import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import { SiCodewars } from 'react-icons/si'
import { BsFillMoonStarsFill, BsGithub } from "react-icons/bs";
import { BiLinkExternal } from "react-icons/bi"
import { useState } from "react";
import Image from "next/legacy/image";

import web1 from "../public/web1.jpg";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.jpg";
import web4 from "../public/web4.png";

import mynotes from "../public/mynotes.jpg"
import setlistener from "../public/setlistener.png"
import diagnose from "../public/diagnose.png"
import quotestv from "../public/quotestv.png"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [pic, setPic] = useState(false);

  const clickHandler = () => {
    console.log("clicked");
    setDarkMode(!darkMode)
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Rishad Nero Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section>
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">rsnr code</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={clickHandler}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href='../rsnrResume.pdf' download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Rishad Nero
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              FULL-STACK WEB DEVELOPER
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              MERN stack programmer seeking a full-time role where I can help a company achieve their goals. Check out my personal projects down below and get in touch with me!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.codewars.com/users/rsnrcode" target="_blank" rel="noopener noreferrer"><SiCodewars className="text-5xl"/></a>
              <a href="https://www.linkedin.com/in/rishadnero/" target="_blank" rel="noopener noreferrer"><AiFillLinkedin /></a>
              <a href="https://github.com/rsnr-code" target="_blank" rel="noopener noreferrer"><AiFillGithub /></a>
            </div>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-center mt-5">ABOUT ME</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center">
              I love building things with code. Whether it's for a client or a personal project, I always find myself enjoying my work. My first experience with web development was at the age of 14 when I would make fansites for my favourite TV shows. It started off as a hobby I showed off to my friends but quickly turned into something more. I continue to expand my knowledge through my personal projects and collaborations with other developers at 100devs. 
            </p>

            <div className="sm:w-10 columns-3 lg:flex lg:justify-center mx-auto gap-16 py-3 m-10">
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" />
            
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" />
          
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" />
                               
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg" />

            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg"  className="dark:invert"/>

            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" />

            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg"  className="dark:invert"/>
          
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg" />
                    
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg"/>
              
            </div>
          </div>
            


            
            <h3 className="text-3xl py-1 mt-12 text-center dark:text-white">PROJECTS</h3>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <div className="flex justify-end gap-3 text-2xl dark:invert">
              <BiLinkExternal />
              <BsGithub />
              </div>
           <Image className="object-scale-down dark:invert"
                width={"8%"}
                height={"1%"}
                layout="responsive"
                src={diagnose} />
              <Image
                className="object-scale-down"
                width={"100%"}
                height={"70%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <div className="flex justify-end gap-3 text-2xl dark:invert">
              <BiLinkExternal />
              <BsGithub />
              </div>
              <Image className="object-scale-down dark:invert"
                width={"8%"}
                height={"1%"}
                layout="responsive"
                src={setlistener} />
              <Image
                className="object-scale-down"
                width={"100%"}
                height={"70%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <div className="flex justify-end gap-3 text-2xl dark:invert">
              <BiLinkExternal />
              <BsGithub />
              </div>
            <Image className="object-scale-down dark:invert"
                width={"10%"}
                height={"1%"}
                layout="responsive"
                src={mynotes} />
                
              <Image
               className="object-scale-down"
                width={"100%"}
                height={"70%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
            <div className="flex justify-end gap-3 text-2xl dark:invert">
              <BiLinkExternal />
              <BsGithub />
              </div>
            <Image className="object-scale-down dark:invert"
                width={"12%"}
                height={"1%"}
                layout="responsive"
                src={quotestv} />
              <Image
                 className="object-scale-down"
                width={"100%"}
                height={"70%"}
                layout="responsive"
                src={web4}
              />
            </div>         
          </div>
        </section>
      </main>
    </div>
  );
}